#!/bin/sh
/usr/local/bin/weave launch 104.199.160.171
/usr/local/bin/scope launch 104.199.160.171
weave expose
sleep 15
/usr/bin/consul agent -atlas faddat/chicken -server -bind=$(curl www.canhazip.com) -advertise=$(curl www.canhazip.com) -bootstrap-expect=3 -atlas-join -data-dir=/data/consul -atlas-token=yfIkFrF1SUKn5g.atlasv1.9laHhtFl6uAFyNO6qlZxXknpYJKdmix84c66mNryQ8wUHg0fPxqQvpfwlC79WAz4eqc
