#!/bin/sh
/usr/local/bin/weave launch 104.199.160.171
/usr/local/bin/scope launch 104.199.160.171
weave expose
sleep 15
/usr/bin/consul agent -atlas faddat/chicken -client -bind=$(curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/‌​0/external-ip) -advertise=$(curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/‌​0/external-ip) -atlas-join -data-dir=/data/consul -atlas-token=yfIkFrF1SUKn5g.atlasv1.9laHhtFl6uAFyNO6qlZxXknpYJKdmix84c66mNryQ8wUHg0fPxqQvpfwlC79WAz4eqc
